package com.example.model

class Country(
    val code: String = "",
    val name: String = "",
    val flag: String = "",
    val language: String = ""
)

class CountryData {
    companion object {
        val countries: List<Country> = listOf(
            Country("AF", "Afghanistan", "🇦🇫", "Add primary language"),
            Country("AL", "Albania", "🇦🇱", "Add primary language"),
            Country("DZ", "Algeria", "🇩🇿", "Add primary language"),
            Country("AS", "American Samoa", "🇦🇸", "Add primary language"),
            Country("AD", "Andorra", "🇦🇩", "Add primary language"),
            Country("AO", "Angola", "🇦🇴", "Add primary language"),
            Country("AI", "Anguilla", "🇦🇮", "Add primary language"),
            Country("AQ", "Antarctica", "🇦🇶", "Add primary language"),
            Country("AG", "Antigua and Barbuda", "🇦🇬", "Add primary language"),
            Country("AR", "Argentina", "🇦🇷", "Add primary language"),
            Country("AM", "Armenia", "🇦🇲", "Add primary language"),
            Country("AW", "Aruba", "🇦🇼", "Add primary language"),
            Country("AU", "Australia", "🇦🇺", "Add primary language"),
            Country("AT", "Austria", "🇦🇹", "Add primary language"),
            Country("AZ", "Azerbaijan", "🇦🇿", "Add primary language"),
            Country("BS", "Bahamas", "🇧🇸", "Add primary language"),
            Country("BH", "Bahrain", "🇧🇭", "Add primary language"),
            Country("BD", "Bangladesh", "🇧🇩", "Add primary language"),
            Country("BB", "Barbados", "🇧🇧", "Add primary language"),
            Country("BY", "Belarus", "🇧🇾", "Add primary language"),
            Country("BE", "Belgium", "🇧🇪", "Add primary language"),
            Country("BZ", "Belize", "🇧🇿", "Add primary language"),
            Country("BJ", "Benin", "🇧🇯", "Add primary language"),
            Country("BM", "Bermuda", "🇧🇲", "Add primary language"),
            Country("BT", "Bhutan", "🇧🇹", "Add primary language"),
            Country("BO", "Bolivia, Plurinational State of", "🇧🇴", "Add primary language"),
            Country("BQ", "Bonaire, Sint Eustatius and Saba", "🇧🇶", "Add primary language"),
            Country("BA", "Bosnia and Herzegovina", "🇧🇦", "Add primary language"),
            Country("BW", "Botswana", "🇧🇼", "Add primary language"),
            Country("BV", "Bouvet Island", "🇧🇻", "Add primary language"),
            Country("BR", "Brazil", "🇧🇷", "Add primary language"),
            Country("IO", "British Indian Ocean Territory", "🇮🇴", "Add primary language"),
            Country("BN", "Brunei Darussalam", "🇧🇳", "Add primary language"),
            Country("BG", "Bulgaria", "🇧🇬", "Add primary language"),
            Country("BF", "Burkina Faso", "🇧🇫", "Add primary language"),
            Country("BI", "Burundi", "🇧🇮", "Add primary language"),
            Country("CV", "Cabo Verde", "🇨🇻", "Add primary language"),
            Country("KH", "Cambodia", "🇰🇭", "Add primary language"),
            Country("CM", "Cameroon", "🇨🇲", "Add primary language"),
            Country("CA", "Canada", "🇨🇦", "Add primary language"),
            Country("KY", "Cayman Islands", "🇰🇾", "Add primary language"),
            Country("CF", "Central African Republic", "🇨🇫", "Add primary language"),
            Country("TD", "Chad", "🇹🇩", "Add primary language"),
            Country("CL", "Chile", "🇨🇱", "Add primary language"),
            Country("CN", "China", "🇨🇳", "Add primary language"),
            Country("CX", "Christmas Island", "🇨🇽", "Add primary language"),
            Country("CC", "Cocos (Keeling) Islands", "🇨🇨", "Add primary language"),
            Country("CO", "Colombia", "🇨🇴", "Add primary language"),
            Country("KM", "Comoros", "🇰🇲", "Add primary language"),
            Country("CG", "Congo", "🇨🇬", "Add primary language"),
            Country("CD", "Congo, The Democratic Republic of the", "🇨🇩", "Add primary language"),
            Country("CK", "Cook Islands", "🇨🇰", "Add primary language"),
            Country("CR", "Costa Rica", "🇨🇷", "Add primary language"),
            Country("HR", "Croatia", "🇭🇷", "Add primary language"),
            Country("CU", "Cuba", "🇨🇺", "Add primary language"),
            Country("CW", "Curaçao", "🇨🇼", "Add primary language"),
            Country("CY", "Cyprus", "🇨🇾", "Add primary language"),
            Country("CZ", "Czechia", "🇨🇿", "Add primary language"),
            Country("CI", "Côte d'Ivoire", "🇨🇮", "Add primary language"),
            Country("DK", "Denmark", "🇩🇰", "Add primary language"),
            Country("DJ", "Djibouti", "🇩🇯", "Add primary language"),
            Country("DM", "Dominica", "🇩🇲", "Add primary language"),
            Country("DO", "Dominican Republic", "🇩🇴", "Add primary language"),
            Country("EC", "Ecuador", "🇪🇨", "Add primary language"),
            Country("EG", "Egypt", "🇪🇬", "Add primary language"),
            Country("SV", "El Salvador", "🇸🇻", "Add primary language"),
            Country("GQ", "Equatorial Guinea", "🇬🇶", "Add primary language"),
            Country("ER", "Eritrea", "🇪🇷", "Add primary language"),
            Country("EE", "Estonia", "🇪🇪", "Add primary language"),
            Country("SZ", "Eswatini", "🇸🇿", "Add primary language"),
            Country("ET", "Ethiopia", "🇪🇹", "Add primary language"),
            Country("FK", "Falkland Islands (Malvinas)", "🇫🇰", "Add primary language"),
            Country("FO", "Faroe Islands", "🇫🇴", "Add primary language"),
            Country("FJ", "Fiji", "🇫🇯", "Add primary language"),
            Country("FI", "Finland", "🇫🇮", "Add primary language"),
            Country("FR", "France", "🇫🇷", "Add primary language"),
            Country("GF", "French Guiana", "🇬🇫", "Add primary language"),
            Country("PF", "French Polynesia", "🇵🇫", "Add primary language"),
            Country("TF", "French Southern Territories", "🇹🇫", "Add primary language"),
            Country("GA", "Gabon", "🇬🇦", "Add primary language"),
            Country("GM", "Gambia", "🇬🇲", "Add primary language"),
            Country("GE", "Georgia", "🇬🇪", "Add primary language"),
            Country("DE", "Germany", "🇩🇪", "Add primary language"),
            Country("GH", "Ghana", "🇬🇭", "Add primary language"),
            Country("GI", "Gibraltar", "🇬🇮", "Add primary language"),
            Country("GR", "Greece", "🇬🇷", "Add primary language"),
            Country("GL", "Greenland", "🇬🇱", "Add primary language"),
            Country("GD", "Grenada", "🇬🇩", "Add primary language"),
            Country("GP", "Guadeloupe", "🇬🇵", "Add primary language"),
            Country("GU", "Guam", "🇬🇺", "Add primary language"),
            Country("GT", "Guatemala", "🇬🇹", "Add primary language"),
            Country("GG", "Guernsey", "🇬🇬", "Add primary language"),
            Country("GN", "Guinea", "🇬🇳", "Add primary language"),
            Country("GW", "Guinea-Bissau", "🇬🇼", "Add primary language"),
            Country("GY", "Guyana", "🇬🇾", "Add primary language"),
            Country("HT", "Haiti", "🇭🇹", "Add primary language"),
            Country("HM", "Heard Island and McDonald Islands", "🇭🇲", "Add primary language"),
            Country("VA", "Holy See (Vatican City State)", "🇻🇦", "Add primary language"),
            Country("HN", "Honduras", "🇭🇳", "Add primary language"),
            Country("HK", "Hong Kong", "🇭🇰", "Add primary language"),
            Country("HU", "Hungary", "🇭🇺", "Add primary language"),
            Country("IS", "Iceland", "🇮🇸", "Add primary language"),
            Country("IN", "India", "🇮🇳", "Add primary language"),
            Country("ID", "Indonesia", "🇮🇩", "Add primary language"),
            Country("IR", "Iran, Islamic Republic of", "🇮🇷", "Add primary language"),
            Country("IQ", "Iraq", "🇮🇶", "Add primary language"),
            Country("IE", "Ireland", "🇮🇪", "Add primary language"),
            Country("IM", "Isle of Man", "🇮🇲", "Add primary language"),
            Country("IL", "Israel", "🇮🇱", "Add primary language"),
            Country("IT", "Italy", "🇮🇹", "Add primary language"),
            Country("JM", "Jamaica", "🇯🇲", "Add primary language"),
            Country("JP", "Japan", "🇯🇵", "Add primary language"),
            Country("JE", "Jersey", "🇯🇪", "Add primary language"),
            Country("JO", "Jordan", "🇯🇴", "Add primary language"),
            Country("KZ", "Kazakhstan", "🇰🇿", "Add primary language"),
            Country("KE", "Kenya", "🇰🇪", "Add primary language"),
            Country("KI", "Kiribati", "🇰🇮", "Add primary language"),
            Country("KP", "Korea, Democratic People's Republic of", "🇰🇵", "Add primary language"),
            Country("KR", "Korea, Republic of", "🇰🇷", "Add primary language"),
            Country("KW", "Kuwait", "🇰🇼", "Add primary language"),
            Country("KG", "Kyrgyzstan", "🇰🇬", "Add primary language"),
            Country("LA", "Lao People's Democratic Republic", "🇱🇦", "Add primary language"),
            Country("LV", "Latvia", "🇱🇻", "Add primary language"),
            Country("LB", "Lebanon", "🇱🇧", "Add primary language"),
            Country("LS", "Lesotho", "🇱🇸", "Add primary language"),
            Country("LR", "Liberia", "🇱🇷", "Add primary language"),
            Country("LY", "Libya", "🇱🇾", "Add primary language"),
            Country("LI", "Liechtenstein", "🇱🇮", "Add primary language"),
            Country("LT", "Lithuania", "🇱🇹", "Add primary language"),
            Country("LU", "Luxembourg", "🇱🇺", "Add primary language"),
            Country("MO", "Macao", "🇲🇴", "Add primary language"),
            Country("MG", "Madagascar", "🇲🇬", "Add primary language"),
            Country("MW", "Malawi", "🇲🇼", "Add primary language"),
            Country("MY", "Malaysia", "🇲🇾", "Add primary language"),
            Country("MV", "Maldives", "🇲🇻", "Add primary language"),
            Country("ML", "Mali", "🇲🇱", "Add primary language"),
            Country("MT", "Malta", "🇲🇹", "Add primary language"),
            Country("MH", "Marshall Islands", "🇲🇭", "Add primary language"),
            Country("MQ", "Martinique", "🇲🇶", "Add primary language"),
            Country("MR", "Mauritania", "🇲🇷", "Add primary language"),
            Country("MU", "Mauritius", "🇲🇺", "Add primary language"),
            Country("YT", "Mayotte", "🇾🇹", "Add primary language"),
            Country("MX", "Mexico", "🇲🇽", "Add primary language"),
            Country("FM", "Micronesia, Federated States of", "🇫🇲", "Add primary language"),
            Country("MD", "Moldova, Republic of", "🇲🇩", "Add primary language"),
            Country("MC", "Monaco", "🇲🇨", "Add primary language"),
            Country("MN", "Mongolia", "🇲🇳", "Add primary language"),
            Country("ME", "Montenegro", "🇲🇪", "Add primary language"),
            Country("MS", "Montserrat", "🇲🇸", "Add primary language"),
            Country("MA", "Morocco", "🇲🇦", "Add primary language"),
            Country("MZ", "Mozambique", "🇲🇿", "Add primary language"),
            Country("MM", "Myanmar", "🇲🇲", "Add primary language"),
            Country("NA", "Namibia", "🇳🇦", "Add primary language"),
            Country("NR", "Nauru", "🇳🇷", "Add primary language"),
            Country("NP", "Nepal", "🇳🇵", "Add primary language"),
            Country("NL", "Netherlands", "🇳🇱", "Add primary language"),
            Country("NC", "New Caledonia", "🇳🇨", "Add primary language"),
            Country("NZ", "New Zealand", "🇳🇿", "Add primary language"),
            Country("NI", "Nicaragua", "🇳🇮", "Add primary language"),
            Country("NE", "Niger", "🇳🇪", "Add primary language"),
            Country("NG", "Nigeria", "🇳🇬", "Add primary language"),
            Country("NU", "Niue", "🇳🇺", "Add primary language"),
            Country("NF", "Norfolk Island", "🇳🇫", "Add primary language"),
            Country("MK", "North Macedonia", "🇲🇰", "Add primary language"),
            Country("MP", "Northern Mariana Islands", "🇲🇵", "Add primary language"),
            Country("NO", "Norway", "🇳🇴", "Add primary language"),
            Country("OM", "Oman", "🇴🇲", "Add primary language"),
            Country("PK", "Pakistan", "🇵🇰", "Add primary language"),
            Country("PW", "Palau", "🇵🇼", "Add primary language"),
            Country("PS", "Palestine, State of", "🇵🇸", "Add primary language"),
            Country("PA", "Panama", "🇵🇦", "Add primary language"),
            Country("PG", "Papua New Guinea", "🇵🇬", "Add primary language"),
            Country("PY", "Paraguay", "🇵🇾", "Add primary language"),
            Country("PE", "Peru", "🇵🇪", "Add primary language"),
            Country("PH", "Philippines", "🇵🇭", "Add primary language"),
            Country("PN", "Pitcairn", "🇵🇳", "Add primary language"),
            Country("PL", "Poland", "🇵🇱", "Add primary language"),
            Country("PT", "Portugal", "🇵🇹", "Add primary language"),
            Country("PR", "Puerto Rico", "🇵🇷", "Add primary language"),
            Country("QA", "Qatar", "🇶🇦", "Add primary language"),
            Country("RO", "Romania", "🇷🇴", "Add primary language"),
            Country("RU", "Russian Federation", "🇷🇺", "Add primary language"),
            Country("RW", "Rwanda", "🇷🇼", "Add primary language"),
            Country("RE", "Réunion", "🇷🇪", "Add primary language"),
            Country("BL", "Saint Barthélemy", "🇧🇱", "Add primary language"),
            Country("SH", "Saint Helena, Ascension and Tristan da Cunha", "🇸🇭", "Add primary language"),
            Country("KN", "Saint Kitts and Nevis", "🇰🇳", "Add primary language"),
            Country("LC", "Saint Lucia", "🇱🇨", "Add primary language"),
            Country("MF", "Saint Martin (French part)", "🇲🇫", "Add primary language"),
            Country("PM", "Saint Pierre and Miquelon", "🇵🇲", "Add primary language"),
            Country("VC", "Saint Vincent and the Grenadines", "🇻🇨", "Add primary language"),
            Country("WS", "Samoa", "🇼🇸", "Add primary language"),
            Country("SM", "San Marino", "🇸🇲", "Add primary language"),
            Country("ST", "Sao Tome and Principe", "🇸🇹", "Add primary language"),
            Country("SA", "Saudi Arabia", "🇸🇦", "Add primary language"),
            Country("SN", "Senegal", "🇸🇳", "Add primary language"),
            Country("RS", "Serbia", "🇷🇸", "Add primary language"),
            Country("SC", "Seychelles", "🇸🇨", "Add primary language"),
            Country("SL", "Sierra Leone", "🇸🇱", "Add primary language"),
            Country("SG", "Singapore", "🇸🇬", "Add primary language"),
            Country("SX", "Sint Maarten (Dutch part)", "🇸🇽", "Add primary language"),
            Country("SK", "Slovakia", "🇸🇰", "Add primary language"),
            Country("SI", "Slovenia", "🇸🇮", "Add primary language"),
            Country("SB", "Solomon Islands", "🇸🇧", "Add primary language"),
            Country("SO", "Somalia", "🇸🇴", "Add primary language"),
            Country("ZA", "South Africa", "🇿🇦", "Add primary language"),
            Country("GS", "South Georgia and the South Sandwich Islands", "🇬🇸", "Add primary language"),
            Country("SS", "South Sudan", "🇸🇸", "Add primary language"),
            Country("ES", "Spain", "🇪🇸", "Add primary language"),
            Country("LK", "Sri Lanka", "🇱🇰", "Add primary language"),
            Country("SD", "Sudan", "🇸🇩", "Add primary language"),
            Country("SR", "Suriname", "🇸🇷", "Add primary language"),
            Country("SJ", "Svalbard and Jan Mayen", "🇸🇯", "Add primary language"),
            Country("SE", "Sweden", "🇸🇪", "Add primary language"),
            Country("CH", "Switzerland", "🇨🇭", "Add primary language"),
            Country("SY", "Syrian Arab Republic", "🇸🇾", "Add primary language"),
            Country("TW", "Taiwan, Province of China", "🇹🇼", "Add primary language"),
            Country("TJ", "Tajikistan", "🇹🇯", "Add primary language"),
            Country("TZ", "Tanzania, United Republic of", "🇹🇿", "Add primary language"),
            Country("TH", "Thailand", "🇹🇭", "Add primary language"),
            Country("TL", "Timor-Leste", "🇹🇱", "Add primary language"),
            Country("TG", "Togo", "🇹🇬", "Add primary language"),
            Country("TK", "Tokelau", "🇹🇰", "Add primary language"),
            Country("TO", "Tonga", "🇹🇴", "Add primary language"),
            Country("TT", "Trinidad and Tobago", "🇹🇹", "Add primary language"),
            Country("TN", "Tunisia", "🇹🇳", "Add primary language"),
            Country("TM", "Turkmenistan", "🇹🇲", "Add primary language"),
            Country("TC", "Turks and Caicos Islands", "🇹🇨", "Add primary language"),
            Country("TV", "Tuvalu", "🇹🇻", "Add primary language"),
            Country("TR", "Türkiye", "🇹🇷", "Add primary language"),
            Country("UG", "Uganda", "🇺🇬", "Add primary language"),
            Country("UA", "Ukraine", "🇺🇦", "Add primary language"),
            Country("AE", "United Arab Emirates", "🇦🇪", "Add primary language"),
            Country("GB", "United Kingdom", "🇬🇧", "Add primary language"),
            Country("US", "United States", "🇺🇸", "Add primary language"),
            Country("UM", "United States Minor Outlying Islands", "🇺🇲", "Add primary language"),
            Country("UY", "Uruguay", "🇺🇾", "Add primary language"),
            Country("UZ", "Uzbekistan", "🇺🇿", "Add primary language"),
            Country("VU", "Vanuatu", "🇻🇺", "Add primary language"),
            Country("VE", "Venezuela, Bolivarian Republic of", "🇻🇪", "Add primary language"),
            Country("VN", "Viet Nam", "🇻🇳", "Add primary language"),
            Country("VG", "Virgin Islands, British", "🇻🇬", "Add primary language"),
            Country("VI", "Virgin Islands, U.S.", "🇻🇮", "Add primary language"),
            Country("WF", "Wallis and Futuna", "🇼🇫", "Add primary language"),
            Country("EH", "Western Sahara", "🇪🇭", "Add primary language"),
            Country("YE", "Yemen", "🇾🇪", "Add primary language"),
            Country("ZM", "Zambia", "🇿🇲", "Add primary language"),
            Country("ZW", "Zimbabwe", "🇿🇼", "Add primary language"),
            Country("AX", "Åland Islands", "🇦🇽", "Add primary language")
        )
    }
}

class CircleAlert(
    val id: String = "",
    val docId: String = "",
    val title: String = "",
    val description: String = "",
    val mediaUri: String = "",
    val mediaType: String = "",
    val contactNumber: String = "",
    val country: String = "",
    val location: String = "",
    val timestamp: Long = 0L,
    val status: String = ""
)

class UserProfile(
    val id: String = "",
    val queue: Int = 0,
    val data1: String = ""
)

class Dua(val id: String = "", val title: String = "", val arabic: String = "", val pronunciation: String = "", val translation: String = "", val reference: String = "", val category: String = "")
class Hadith(val id: String = "", val title: String = "", val arabic: String = "", val pronunciation: String = "", val translation: String = "", val reference: String = "", val category: String = "")
